[package]
name = "cat5"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
bit-vec = "0.6"
cairo-rs = {version = "0.15", features = ["png", "svg", "pdf"]}
chrono = "0.4"
clap = {version = "3.1", features = ["derive"]}
csv = "1.1"
hex = "0.4"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
resvg = "0.15"
tiny-skia = "0.5"
usvg = "0.15"

[build-dependencies]
chrono = "0.4"
walkdir = "2.3"

[[bin]]
name = "cat5d"
path  = "src/cat5d/main.rs"

